In [5]:
#Download CSV Files & Load Data into SQL (Python & SQL

import mysql.connector as db
import pandas as pd

In [7]:
user = 'Saranya'
Passcode = "0120@Peace"
host = 'localhost'
db_name = "demo"

In [9]:
db_connection = db.connect(

                host = host,
                user = user,
                password = Passcode,
                database = db_name
)

In [11]:
db_connection

In [13]:
curr = db_connection.cursor()

In [128]:
sql = """
SELECT*FROM demo.geography
"""

In [130]:
curr.execute(sql)

In [21]:
Cust_Geo = curr.fetchall()

In [25]:
curr.column_names

('GeographyID', 'Country', 'City')

In [31]:
Geography_table =pd.DataFrame(Cust_Geo,columns = curr.column_names)

In [76]:
#Geography - Table 1

Geography_table

   GeographyID      Country       City
0            1           UK     London
1            2      Germany     Berlin
2            3       France      Paris
3            4        Spain     Madrid
4            5        Italy       Rome
5            6  Netherlands  Amsterdam
6            7      Belgium   Brussels
7            8       Sweden  Stockholm
8            9  Switzerland     Zurich
9           10      Austria     Vienna

In [39]:
sql = """
SELECT*FROM demo.products
"""

In [41]:
curr.execute(sql)

In [43]:
Products = curr.fetchall()

In [45]:
curr.column_names

('ProductID', 'ProductName', 'Category', 'Price')

In [47]:
Product_table =pd.DataFrame(Products,columns = curr.column_names)

In [49]:
#Product - Table 2

Product_table

    ProductID      ProductName Category   Price
0           1    Running Shoes   Sports  223.75
1           2  Fitness Tracker   Sports  196.68
2           3         Yoga Mat   Sports  485.32
3           4        Dumbbells   Sports   26.21
4           5      Soccer Ball   Sports   41.26
5           6    Tennis Racket   Sports   36.07
6           7       Basketball   Sports  225.12
7           8  Football Helmet   Sports   44.75
8           9   Baseball Glove   Sports  327.36
9          10       Golf Clubs   Sports   81.59
10         11        Ski Boots   Sports  340.20
11         12       Ice Skates   Sports   37.56
12         13     Swim Goggles   Sports  145.97
13         14   Cycling Helmet   Sports  472.32
14         15    Climbing Rope   Sports  410.17
15         16            Kayak   Sports  259.40
16         17        Surfboard   Sports  275.43
17         18       Volleyball   Sports   42.80
18         19     Hockey Stick   Sports  173.83
19         20    Boxing Gloves   Sports  262.32

In [53]:
sql = """
SELECT*FROM demo.customer_journey
"""

In [55]:
import pandas as pd

In [57]:
curr = db_connection.cursor()

In [59]:
curr.execute(sql)

In [61]:
Journey = curr.fetchall()

In [63]:
curr.column_names

('JourneyID',
 'CustomerID',
 'ProductID',
 'VisitDate',
 'Stage',
 'Action',
 'Duration')

In [65]:
Cust_Journey =pd.DataFrame(Journey,columns = curr.column_names)

In [67]:
#Journey - Table 3


Cust_Journey

,JourneyID,CustomerID,ProductID,VisitDate,Stage,Action,Duration
0,1,64,18,2024-06-10,Checkout,Drop-off,
1,2,94,11,2025-07-09,Checkout,Drop-off,
2,3,34,8,2024-06-14,ProductPage,View,235.0
3,4,33,18,2025-05-28,Checkout,Drop-off,
4,5,91,10,2023-02-11,Homepage,Click,156.0
...,...,...,...,...,...,...,...
95,96,22,9,2024-07-28,ProductPage,View,212.0
96,97,92,19,2025-05-26,homepage,View,203.0
97,98,95,8,2025-05-25,Homepage,Click,68.0
98,99,58,16,2024-07-06,Checkout,Purchase,87.0
99,100,92,10,2024-04-06,ProductPage,View,237.0

In [69]:
sql = """
SELECT*FROM demo.engagement_data
"""

In [71]:
curr = db_connection.cursor()

In [73]:
curr.execute(sql)

In [75]:
Engage_data = curr.fetchall()

In [77]:
curr.column_names

('EngagementID',
 'ContentID',
 'ContentType',
 'Likes',
 'EngagementDate',
 'CampaignID',
 'ProductID',
 'ViewsClicksCombined')

In [79]:
Engage_Data =pd.DataFrame(Engage_data,columns = curr.column_names)

In [81]:
#Customer Engagement - 4

Engage_Data

,EngagementID,ContentID,ContentType,Likes,EngagementDate,CampaignID,ProductID,ViewsClicksCombined
0,1,39,Blog,190,2023-08-30,1,9,1883-671
1,2,48,Blog,114,2023-03-28,18,20,5280-532
2,3,16,video,32,2023-12-08,7,14,1905-204
3,4,43,Video,17,2025-01-21,19,20,2766-257
4,5,16,newsletter,306,2024-02-21,6,15,5116-1524
...,...,...,...,...,...,...,...,...
95,96,17,Blog,32,2024-07-15,14,13,712-142
96,97,34,blog,3,2025-07-01,16,7,696-47
97,98,44,blog,0,2025-08-20,11,8,231-10
98,99,26,Blog,119,2024-04-15,17,4,3511-479
99,100,32,Video,34,2024-05-05,15,13,2657-175

In [83]:
sql = """
SELECT*FROM demo.customer_reviews
"""

In [85]:
curr = db_connection.cursor()

In [87]:
curr.execute(sql)

In [89]:
Cust_review = curr.fetchall()

In [91]:
curr.column_names

('ReviewID', 'CustomerID', 'ProductID', 'ReviewDate', 'Rating', 'ReviewText')

In [93]:
Customer_reviews =pd.DataFrame(Cust_review,columns = curr.column_names)

In [95]:
#Customer Review Table - 5 


Customer_reviews

,ReviewID,CustomerID,ProductID,ReviewDate,Rating,ReviewText
0,1,77,18,2023-12-23,3,"Average experience, nothing special."
1,2,80,19,2024-12-25,5,The quality is top-notch.
2,3,50,13,2025-01-26,4,Five stars for the quick delivery.
3,4,78,15,2025-04-21,3,"Good quality, but could be cheaper."
4,5,64,2,2023-07-16,3,"Average experience, nothing special."
...,...,...,...,...,...,...
95,96,19,13,2023-09-02,3,"Good quality, but could be cheaper."
96,97,64,6,2024-01-19,3,"The product is okay, but the instruction..."
97,98,96,3,2025-11-20,5,Exceeded my expectations!
98,99,79,16,2025-01-29,2,"Average experience, nothing special."
99,100,9,2,2025-06-20,3,Not worth the money.

In [120]:
sql = """
SELECT*FROM demo.customers
"""

In [122]:
curr = db_connection.cursor()

In [124]:
curr.execute(sql)

In [126]:
Customers = curr.fetchall()

In [130]:
curr.column_names

('CustomerID', 'CustomerName', 'Email', 'Gender', 'Age', 'GeographyID')

In [132]:
Customers = pd.DataFrame(Customers,columns = curr.column_names)

In [138]:
#Customers Table - 6

Customers

,CustomerID,CustomerName,Email,Gender,Age,GeographyID
0,1,Emma Anderson,emma.anderson@example.com,Male,50,2
1,2,Sarah Brown,sarah.brown@example.com,Female,37,4
2,3,Robert Hernandez,robert.hernandez@example.com,Female,26,6
3,4,David Garcia,david.garcia@example.com,Male,25,8
4,5,Emma Miller,emma.miller@example.com,Female,41,4
...,...,...,...,...,...,...
95,96,Emily Gonzalez,emily.gonzalez@example.com,Female,38,10
96,97,Emily Rodriguez,emily.rodriguez@example.com,Female,51,3
97,98,Chris Lopez,chris.lopez@example.com,Female,55,10
98,99,Laura Hernandez,laura.hernandez@example.com,Male,41,5
99,100,Jane Brown,jane.brown@example.com,Female,45,10

In [52]:
#Data Extraction & Transformation (SQL & Python)



sql = """
select*from engagement_data where ProductID and Likes > 100
order by ProductID ASC;

"""

In [56]:
curr = db_connection.cursor()

In [58]:
curr.execute(sql)

In [60]:
ProductID = curr.fetchall()

In [62]:
curr.column_names

('EngagementID',
 'ContentID',
 'ContentType',
 'Likes',
 'EngagementDate',
 'CampaignID',
 'ProductID',
 'ViewsClicksCombined')

In [64]:
Likes = pd.DataFrame(ProductID,columns = curr.column_names)

In [66]:
Likes

,EngagementID,ContentID,ContentType,Likes,EngagementDate,CampaignID,ProductID,ViewsClicksCombined
0,37,32,Video,400,2023-01-24,7,1,9759-3095
1,72,19,BLOG,657,2023-01-06,17,1,6991-2499
2,14,2,Socialmedia,317,2023-08-26,16,2,6837-2251
3,87,8,BLOG,111,2024-07-27,2,2,3142-602
4,76,48,Blog,545,2023-03-11,14,3,6205-2834
5,40,18,Video,215,2024-04-02,4,4,3222-793
6,99,26,Blog,119,2024-04-15,17,4,3511-479
7,88,28,socialmedia,121,2023-10-01,12,7,1360-440
8,42,16,Blog,840,2023-07-23,17,8,6771-2617
9,1,39,Blog,190,2023-08-30,1,9,1883-671
10,19,30,Newsletter,118,2023-10-29,11,9,1442-400
11,90,35,Video,595,2023-05-25,7,9,3338-1402
12,12,29,socialmedia,396,2023-06-15,3,10,7877-2037
13,39,24,Video,373,2023-09-02,11,11,4881-1204
14,41,8,Socialmedia,193,2024-06-01,2,12,4654-1083
15,71,37,Video,459,2023-03-04,11,14,4368-1156
16,84,24,socialmedia,116,2023-05-22,18,14,6319-832
17,5,16,newsletter,306,2024-02-21,6,15,5116-1524
18,38,30,Newsletter,449,2023-01-02,16,15,2674-956
19,9,48,blog,123,2024-03-19,13,16,5571-1527
20,16,2,SOCIALMEDIA,276,2023-07-06,17,16,5980-1227
21,22,11,video,357,2024-04-04,12,16,5543-1288
22,79,36,video,397,2023-04-26,9,16,3632-1500
23,93,23,SOCIALMEDIA,147,2023-02-19,1,17,2989-1283
24,94,33,Video,389,2023-02-18,15,17,2595-933
25,77,26,Socialmedia,143,2023-08-27,20,18,1671-482
26,6,32,Socialmedia,648,2023-06-18,18,19,8237-1641
27,67,29,Newsletter,176,2024-06-10,2,19,5147-788
28,2,48,Blog,114,2023-03-28,18,20,5280-532
29,82,49,Socialmedia,142,2023-04-26,8,20,1354-425

In [97]:
#Customer Journey & Engagement Analysis (SQL)

sql = """select Action,
	COUNT(action) AS
	Overall_count
	from customer_journey
	where Stage = 'Checkout'
	group by Action
	order by Overall_count DESC;
"""

In [99]:
import pandas as pd

In [101]:
curr = db_connection.cursor()

In [103]:
curr.execute(sql)

In [105]:
Journey = curr.fetchall()

In [107]:
curr.column_names

('Action', 'Overall_count')

In [109]:
Dropoff = pd.DataFrame(Journey,columns = curr.column_names)

In [111]:
#In checkout stage where customers dropping off in their Journey


Dropoff

     Action  Overall_count
0  Drop-off             14
1  Purchase              6

In [1]:
#common actions leading to successful conversions.


sql = """Select
    Action, 
    COUNT(DISTINCT CustomerID) AS total_customers, 
    COUNT(DISTINCT CASE WHEN JourneyID = 'Yes' THEN CustomerID END) AS converted_customers,
    ROUND(
        (COUNT(DISTINCT CASE WHEN JourneyID = 'Yes' THEN CustomerID END) / 
        COUNT(DISTINCT CustomerID)) * 100, 
        2
    ) AS conversion_rate
FROM customer_journey
GROUP BY Action
ORDER BY conversion_rate DESC;"""

In [23]:
curr = db_connection.cursor()

In [25]:
curr.execute(sql)

In [27]:
Conversion_rate = curr.fetchall()

In [29]:
curr.column_names

('Action', 'total_customers', 'converted_customers', 'conversion_rate')

In [31]:
Conversion_rate = pd.DataFrame(Conversion_rate,columns = curr.column_names)

In [33]:
Conversion_rate

     Action  total_customers  converted_customers conversion_rate
0     Click               20                    0            0.00
1  Drop-off               14                    0            0.00
2  Purchase                6                    0            0.00
3      View               46                    0            0.00

In [ ]:
#Customer Reviews Analysis (SQL & Python):

In [1]:
sql = """select Rating, 
	count(ProductID) as
    ProductID
from customer_reviews
group by Rating
order by Rating desc;"""

In [135]:
import pandas as pd

In [15]:
curr = db_connection.cursor()

In [17]:
curr.execute(sql)

In [19]:
Rating = curr.fetchall()

In [21]:
curr.column_names

('Rating', 'ProductID')

In [29]:
Rating = pd.DataFrame(Rating,columns = curr.column_names)

In [25]:
Rating

   Rating  ProductID
0       5         23
1       4         39
2       3         29
3       2          6
4       1          3

In [161]:
sql ="""SELECT customer_journey.CustomerID, CustomerName, Age, Gender,Duration
FROM customer_journey
JOIN customers ON customer_journey.CustomerID =customers.CustomerID
WHERE Duration IS NOT NULL AND customer_journey.Duration
ORDER BY customer_journey.Duration DESC;"""

In [163]:
import pandas as pd

In [165]:
curr = db_connection.cursor()

In [167]:
curr.execute(sql)

In [169]:
Joint = curr.fetchall()

In [171]:
curr.column_names

('CustomerID', 'CustomerName', 'Age', 'Gender', 'Duration')

In [173]:
Engagement_Joints  = pd.DataFrame(Joint,columns = curr.column_names)

In [175]:
Engagement_Joints

    CustomerID      CustomerName  Age  Gender Duration
0           58     Jane Williams   34    Male     87.0
1           54  Michael Gonzalez   24  Female     83.0
2           83       Emily Jones   20    Male     79.0
3           86   James Hernandez   63    Male     77.0
4           93    Jane Rodriguez   41  Female     69.0
..         ...               ...  ...     ...      ...
81          94     Jane Anderson   48    Male    118.0
82           4      David Garcia   25    Male    110.0
83          14     Olivia Wilson   60    Male    104.0
84          54  Michael Gonzalez   24  Female    101.0
85          36      Emma Johnson   63  Female    100.0

[86 rows x 5 columns]

In [177]:
#Marketing Effectiveness (SQL)
#Calculate customer retention rate


sql ="""Select
    Stage, 
    COUNT(DISTINCT CustomerID) AS customers_count
FROM customer_journey
GROUP BY stage
ORDER BY customers_count DESC;"""

In [209]:
curr = db_connection.cursor()

In [211]:
curr.execute(sql)

In [213]:
Journey_Analysis = curr.fetchall()

In [215]:
curr.column_names

('Stage', 'customers_count')

In [217]:
Cust_Analysis  = pd.DataFrame(Journey_Analysis,columns = curr.column_names)

In [219]:
Cust_Analysis

         Stage  customers_count
0     Homepage               40
1  ProductPage               24
2     Checkout               19

In [347]:
#Calculate average duration per stage for engagement insights.


sql = """Select 
    stage, 
    AVG(Duration) AS avg_time_spent
FROM customer_journey
GROUP BY stage;"""

In [349]:
curr = db_connection.cursor()

In [350]:
curr.execute(sql)

In [353]:
Duration = curr.fetchall()

In [355]:
curr.column_names

('stage', 'avg_time_spent')

In [357]:
Avg_Duration  = pd.DataFrame(Duration,columns = curr.column_names)

In [359]:
Avg_Duration

         stage  avg_time_spent
0     Checkout       45.050000
1  ProductPage      182.769231
2     Homepage      160.537037

In [268]:
#Identify highest-rated and lowest-rated products using SQL.

sql = """
Select 
    ProductID, 
    COUNT(*) AS total_reviews,
    ROUND(AVG(rating), 2) AS avg_rating
FROM customer_reviews
GROUP BY ProductID
ORDER BY avg_rating DESC;"""

In [279]:
curr = db_connection.cursor()

In [281]:
curr.execute(sql)

In [283]:
Rating = curr.fetchall()

In [285]:
curr.column_names

('ProductID', 'total_reviews', 'avg_rating')

In [287]:
Avg_Rating  = pd.DataFrame(Rating,columns = curr.column_names)

In [289]:
Avg_Rating

    ProductID  total_reviews avg_rating
0           8              3       5.00
1          19              5       4.40
2          18              3       4.00
3          15              6       4.00
4           1              4       4.00
5          11              6       4.00
6          20              2       4.00
7           5              3       4.00
8          17              9       3.89
9           6              7       3.86
10          3              7       3.71
11         13              9       3.67
12          2              7       3.57
13         10              4       3.50
14          9              5       3.40
15         16             10       3.40
16          4              5       3.00
17         12              2       3.00
18          7              3       2.67

In [333]:
#Correlate review trends with product performance.



sql = """Select 
    ProductID, 
    ROUND(AVG(rating), 2) AS avg_rating, 
    COUNT(*) AS pp_reviews
FROM customer_reviews
GROUP BY ProductID
ORDER BY ProductID;"""

In [335]:
curr = db_connection.cursor()

In [337]:
curr.execute(sql)

In [339]:
Product_Review = curr.fetchall()

In [341]:
curr.column_names

('ProductID', 'avg_rating', 'pp_reviews')

In [343]:
Overall_Reviews  = pd.DataFrame(Product_Review,columns = curr.column_names)

In [345]:
Overall_Reviews

    ProductID avg_rating  pp_reviews
0           1       4.00           4
1           2       3.57           7
2           3       3.71           7
3           4       3.00           5
4           5       4.00           3
5           6       3.86           7
6           7       2.67           3
7           8       5.00           3
8           9       3.40           5
9          10       3.50           4
10         11       4.00           6
11         12       3.00           2
12         13       3.67           9
13         15       4.00           6
14         16       3.40          10
15         17       3.89           9
16         18       4.00           3
17         19       4.40           5
18         20       4.00           2